### ISSUE TITLE
ImageFormatTests.cs meta file issue in dependency: com.unity.perception:0.8.0-preview.3

### ISSUE THREAD

**Issue by makokaz** [Unity-Technologies/Robotics-Warehouse#11]
**Describe the bug**
Warnings in Unity console that `ImageFormatTests.cs` has not been found in package `com.unity.simulation.capture/Tests/`.
Another warning appears because Unity tried to delete the meta-file `ImageFormatTests.cs.meta`, but errors out because the package folder is immutable.

**To Reproduce**
Clone the current version (e.g. `v.0.0.1`) of this repo, or add it as a dependency to your own project.
Opening the project results in the above error.

**Console logs / stack traces**
- ```A meta data file (.meta) exists but its asset 'Packages/com.unity.simulation.capture/Tests/ImageFormatTests.cs' can't be found. When moving or deleting files outside of Unity, please ensure that the corresponding .meta file is moved or deleted along with it.```
- ```Couldn't delete Packages/com.unity.simulation.capture/Tests/ImageFormatTests.cs.meta because it's in an immutable folder.```

**Expected behavior**
The console warning should vanish.

**Screenshots**
<img width="1397" alt="meta_file_issue" src="https://user-images.githubusercontent.com/59295964/138638178-bd7891e7-d4d4-4f8d-ab08-bd78898d7ff5.png">

**Environment (please complete the following information, where applicable):**
- Unity Version: 2020.3.17f1
- Unity machine OS + version: macOS BigSur 11.6
- ROS machine OS + version: Ubuntu 18.04, ROS Noetic
- ROS–Unity communication: Docker
- Branch or version: v0.0.1

**Additional context**
The problem is in the package `com.unity.simulation.capture:0.0.10-preview.20`, which is a dependency of the package `com.unity.perception:0.8.0-preview.3`, which itself is a dependency of the current version of this repo `v0.0.1`.
It has been solved in `com.unity.perception:0.8.0-preview.4`.
Upgrading to this package dependency simply solves the problem.

**Comment by peifeng-unity** [comment]
Hi @makokaz, thank you for bringing this up. I have created an internal ticket (AIRO-1484) to upgrade the version of the perception package and fix this warning.
